---
title: 'Product Launch NFTs'
publishedAt: '2023-04-04'
summary: 'From Passive Collectors to Passionate Users'
---

_From Passive Collectors to Passionate Users_

NFTs create a fun and engaging way to share your browsing history with your friends and broader network. A web3 enthusiast’s portfolio becomes a representation of the projects they’re interested in, the tools they use, the podcasts they listen to, the events they attend, and more. It’s also the signal of these NFTs that makes others want to invest in the same project, go to the same event, or even sometimes hire someone based upon their on-chain reputation.

A new wave of web3 projects are taking that on-chain reputation to the next level with the use of product launch NFTs – drops that bring the launch awareness and that can even unlock features within the app. Some product launch NFTs have been going insanely viral recently, most notably [Base, Introduced](https://zora.co/collections/0xd4307e0acd12cf46fd6cf93bc264f5d5d1598792) by Coinbase which closed with a staggering 485k mints. 

While true users often engage with these drops, the most popular ones often make their way to more mainstream audiences, such as the trending lists on [Zora](https://zora.co) and [mint.fun](https://mint.fun), as well in conversations on [Twitter](https://twitter.com) and [Farcaster](https://warpcast.com). The interesting thing about this trend is that because minting normally comes from a network signal and because you can normally do something with that product launch NFT(eg. check out a project, unlock a feature, etc), it can turn people who’d normally be passive collectors into passionate users.

There are a few different types of product launch NFTs that have emerged. Some projects drop mints that provide no utility other than to raise awareness for the project. However, a few of these projects, such as Base, Introduced and [WINTΞR Season 01](https://opensea.io/collection/wintksr-seasons) have not only done well but also engaged minters by using popular art styles and playing around with things like dynamic NFTs.

A product launch NFT style that’s become very popular is the ‘pass’ – a NFT that allows someone to use an app or access advanced features. This style adds a layer of exclusivity to the mint that only hypes it up more, especially if it’s an invite-only mint. 

[Dawn Pass](https://opensea.io/collection/dawn-pass-by-daylight) by [Daylight](https://daylight.xyz) is a great example of this. Their invite-only NFT pass ended up with 11K+ mints, the project was trending on Farcaster and other platforms, and the team is now doing great things like partnering with [Zerion](https://zerion.io/) to show their abilities inside of Zerion’s wallet. Another example is [Launch Pass](https://www.launchcaster.xyz/launchpass) by [Launchcaster](https://www.launchcaster.xyz/), which gives minters the ability to create a profile and access other features on the platform. Not only was the launch very successful, but it also inspired the team to create a NFT feature on Launchcaster that allows any launch to add an accompanying mint for anyone who upvotes the project.

I’ve also seen creators drop “launch-style” NFTs using different mediums such as video or on-chan participation to convey a message. Two video NFTs I enjoyed and collected are [This Could Be A Moment by Reggie James](https://opensea.io/assets/ethereum/0x2afc7e19c52a7fbd219744b1dc97e3bb605a0e93/62) and [From Disney to Nouns: The Rise of Decentralized Creativity by Drew Coffman](https://opensea.io/assets/ethereum/0x024c14ca63ff1ab594a76579bf5c35fe030b16c4/18). 

In his video, Drew Coffman expresses his thoughts on how [Nouns DAO](https://nouns.wtf/) is a decentralized flywheel for creators and projects, similar to(and potentially more powerful than) the brand flywheel that Disney had. A key quote from the video stands out that captures its essence: “The Nouns flywheel is a brand building mechanism that’s not only democratic and decentralized, it’s incentivized to bring in as many people as possible.”

Through alternate forms of content, web3 brands and creators can feed into their knowledge of online reputation and create NFT experiences that people want to engage with and show off. By incorporating elements like dynamic visuals, exclusive access, or gamification, these projects manage to captivate users and encourage long-term involvement. Others have taken alternate NFT utility even further, such as this [on-chain game of checkers from the Highlight.xyz team](https://opensea.io/assets/ethereum/0x67e118689f7655b06fce49b5c0e0b8ee1b08b0c1/11).

With mints and other on-chain actions showing more about what people are doing, a web3 enthusiast’s online reputation is becoming the most robust representation of their interests, and even more so than any web2 alternative has to offer. It gives people one place to show off who they are and their reputation can be publicly shown everywhere they go in web3.

![Chainstory screenshot](https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142852/media/ChainstoryScreenshot.png)
A great project that highlights people's web3 reputation is [Chainstory](https://chainstory.xyz) — it shows a profile of actions and holdings for a given ENS. This platform offers a unique way of visualizing an individual's engagement within the web3 ecosystem by providing an easy-to-understand snapshot of their decentralized activities, such as their participation in DAOs, DeFi platforms, and NFT collections.

Another project that has added to many people’s web3 identities, as mentioned earlier, is Farcaster. Because of how tight-knit the network is, the network effect of seeing friends minting a project is taken even further. People who use Farcaster a lot want to take suggestions from that community over others and have an even higher incentive to show what they do and say on Farcaster as part of their identity – whether that’s linking their username on a personal site, building projects on the protocol that others see, etc.

![Yup screenshot](https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142860/media/YupScreenshot.png)
Along similar lines, a web3 social aggregator called [Yup](https://yup.io) curates a feed across platforms based upon what the user does as a whole. So if someone uses Farcaster a lot and posts about a certain type of topic, their Lens feed will be filled with content that’s similar to what they’re used to seeing on Farcaster. Taken further, what if a platform like Yup scraped even more data, like transactions, to make it the home for everything you’re doing and sharing in web3? It would fit in very well with the trend of online reputation and give people a single identity and following they can keep regardless of the platform they post to.

As the web3 ecosystem continues to expand and mature, we can expect even more innovative ways to push online reputation and integrate it into various aspects of our lives. With the development of web2 bridges and deeper connections between decentralized platforms and traditional internet services, every app and fan experience will soon be able to offer in-depth metrics and insights on users' online reputations.

One project I'm keeping my eye on is [Stealcam](https://stealcam.com) — a "Patreon meets web3"-esque project that lets people share and reveal photos as NFTs with friends and communities. It takes the concept of a Launch NFT further, going from a one-time utility to repeated engagement. You can read more about it in this thorough [research piece that Leonie released last week](https://nonieengel.substack.com/p/new-pixels-on-the-block).

As the web3 ecosystem continues to expand, projects like Stealcam are setting the stage for the future of online reputation. This evolution will extend beyond the decentralized space, encompassing all the brands and creators we currently interact with in web2. As these entities integrate with web3 technologies, they will capitalize on the potential of online reputation, enabling them to establish deeper connections with their audiences.

With the merging of web2 and web3 ecosystems, users' online reputations will become more influential than ever before. Brands and creators will leverage these reputations to offer personalized experiences and targeted rewards, acknowledging users' contributions and participation within their respective communities. 

What if a brand could more accurately target who their top users were based upon this on-chain reputation, and from there even see other interests? And on the flip side, people could receive exclusive offers and even potentially payments for interacting with brands or services. Consequently, our online and offline lives will become increasingly interconnected, with web3 reputations shaping not only our digital experiences but also our real-world interactions. In this new era, the value of one's online reputation will be more significant than ever, creating exciting opportunities for users to engage with brands and creators in meaningful ways.