/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssRouteImport } from './routes/rss'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as InfoRouteImport } from './routes/info'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIndexRouteImport } from './routes/video.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as ApiFeedRouteImport } from './routes/api.feed'
import { Route as DotwellKnownFarcasterDotjsonRouteImport } from './routes/[.]well-known.farcaster[.]json'
import { Route as ApiFeedFarcasterRouteImport } from './routes/api.feed.farcaster'
import { Route as ApiOgBlogIdRouteImport } from './routes/api.og.blog.$id'
import { Route as ApiBlogIdMarkdownRouteImport } from './routes/api.blog.$id.markdown'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownFarcasterDotjsonRoute =
  DotwellKnownFarcasterDotjsonRouteImport.update({
    id: '/.well-known/farcaster.json',
    path: '/.well-known/farcaster.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFeedFarcasterRoute = ApiFeedFarcasterRouteImport.update({
  id: '/farcaster',
  path: '/farcaster',
  getParentRoute: () => ApiFeedRoute,
} as any)
const ApiOgBlogIdRoute = ApiOgBlogIdRouteImport.update({
  id: '/api/og/blog/$id',
  path: '/api/og/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIdMarkdownRoute = ApiBlogIdMarkdownRouteImport.update({
  id: '/api/blog/$id/markdown',
  path: '/api/blog/$id/markdown',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/apps': typeof AppsRoute
  '/feed': typeof FeedRoute
  '/info': typeof InfoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss': typeof RssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/blog/$id': typeof BlogIdRoute
  '/video/$id': typeof VideoIdRoute
  '/blog/': typeof BlogIndexRoute
  '/video/': typeof VideoIndexRoute
  '/api/feed/farcaster': typeof ApiFeedFarcasterRoute
  '/api/blog/$id/markdown': typeof ApiBlogIdMarkdownRoute
  '/api/og/blog/$id': typeof ApiOgBlogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/apps': typeof AppsRoute
  '/feed': typeof FeedRoute
  '/info': typeof InfoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss': typeof RssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/blog/$id': typeof BlogIdRoute
  '/video/$id': typeof VideoIdRoute
  '/blog': typeof BlogIndexRoute
  '/video': typeof VideoIndexRoute
  '/api/feed/farcaster': typeof ApiFeedFarcasterRoute
  '/api/blog/$id/markdown': typeof ApiBlogIdMarkdownRoute
  '/api/og/blog/$id': typeof ApiOgBlogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/apps': typeof AppsRoute
  '/feed': typeof FeedRoute
  '/info': typeof InfoRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss': typeof RssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/feed': typeof ApiFeedRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/blog/$id': typeof BlogIdRoute
  '/video/$id': typeof VideoIdRoute
  '/blog/': typeof BlogIndexRoute
  '/video/': typeof VideoIndexRoute
  '/api/feed/farcaster': typeof ApiFeedFarcasterRoute
  '/api/blog/$id/markdown': typeof ApiBlogIdMarkdownRoute
  '/api/og/blog/$id': typeof ApiOgBlogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/apps'
    | '/feed'
    | '/info'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss'
    | '/sitemap.xml'
    | '/.well-known/farcaster.json'
    | '/api/feed'
    | '/articles/$id'
    | '/blog/$id'
    | '/video/$id'
    | '/blog/'
    | '/video/'
    | '/api/feed/farcaster'
    | '/api/blog/$id/markdown'
    | '/api/og/blog/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/apps'
    | '/feed'
    | '/info'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss'
    | '/sitemap.xml'
    | '/.well-known/farcaster.json'
    | '/api/feed'
    | '/articles/$id'
    | '/blog/$id'
    | '/video/$id'
    | '/blog'
    | '/video'
    | '/api/feed/farcaster'
    | '/api/blog/$id/markdown'
    | '/api/og/blog/$id'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/apps'
    | '/feed'
    | '/info'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/rss'
    | '/sitemap.xml'
    | '/.well-known/farcaster.json'
    | '/api/feed'
    | '/articles/$id'
    | '/blog/$id'
    | '/video/$id'
    | '/blog/'
    | '/video/'
    | '/api/feed/farcaster'
    | '/api/blog/$id/markdown'
    | '/api/og/blog/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppsRoute: typeof AppsRoute
  FeedRoute: typeof FeedRoute
  InfoRoute: typeof InfoRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssRoute: typeof RssRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownFarcasterDotjsonRoute: typeof DotwellKnownFarcasterDotjsonRoute
  ApiFeedRoute: typeof ApiFeedRouteWithChildren
  ArticlesIdRoute: typeof ArticlesIdRoute
  BlogIdRoute: typeof BlogIdRoute
  VideoIdRoute: typeof VideoIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  VideoIndexRoute: typeof VideoIndexRoute
  ApiBlogIdMarkdownRoute: typeof ApiBlogIdMarkdownRoute
  ApiOgBlogIdRoute: typeof ApiOgBlogIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video/'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/farcaster.json': {
      id: '/.well-known/farcaster.json'
      path: '/.well-known/farcaster.json'
      fullPath: '/.well-known/farcaster.json'
      preLoaderRoute: typeof DotwellKnownFarcasterDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/farcaster': {
      id: '/api/feed/farcaster'
      path: '/farcaster'
      fullPath: '/api/feed/farcaster'
      preLoaderRoute: typeof ApiFeedFarcasterRouteImport
      parentRoute: typeof ApiFeedRoute
    }
    '/api/og/blog/$id': {
      id: '/api/og/blog/$id'
      path: '/api/og/blog/$id'
      fullPath: '/api/og/blog/$id'
      preLoaderRoute: typeof ApiOgBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$id/markdown': {
      id: '/api/blog/$id/markdown'
      path: '/api/blog/$id/markdown'
      fullPath: '/api/blog/$id/markdown'
      preLoaderRoute: typeof ApiBlogIdMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiFeedRouteChildren {
  ApiFeedFarcasterRoute: typeof ApiFeedFarcasterRoute
}

const ApiFeedRouteChildren: ApiFeedRouteChildren = {
  ApiFeedFarcasterRoute: ApiFeedFarcasterRoute,
}

const ApiFeedRouteWithChildren =
  ApiFeedRoute._addFileChildren(ApiFeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppsRoute: AppsRoute,
  FeedRoute: FeedRoute,
  InfoRoute: InfoRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssRoute: RssRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownFarcasterDotjsonRoute: DotwellKnownFarcasterDotjsonRoute,
  ApiFeedRoute: ApiFeedRouteWithChildren,
  ArticlesIdRoute: ArticlesIdRoute,
  BlogIdRoute: BlogIdRoute,
  VideoIdRoute: VideoIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  VideoIndexRoute: VideoIndexRoute,
  ApiBlogIdMarkdownRoute: ApiBlogIdMarkdownRoute,
  ApiOgBlogIdRoute: ApiOgBlogIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
