import { MediaItem } from "app/types";

export const posts: MediaItem[] = [
    {
      "id": "its-time-to-rebuild-the-internet",
      "date": "July 11, 2019",
      "title": "It’s Time to Rebuild the Internet",
      "description": "It’s Time to Rebuild the Internet",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142851/media/AppleMacintosh128K.jpg",
      "type": "blog"
    },
    {
      "id": "how-i-ended-up-spending-all-summer-building-a-chrome-extension",
      "date": "September 13, 2019",
      "title": "How I ended up spending all summer building a Chrome extension",
      "description": "How I ended up spending all summer building a Chrome extension",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142851/media/ActionsChromeExtBanner.jpg",
      "type": "blog",
    },
    {
      "id": "tools-for-action",
      "date": "January 11, 2021",
      "title": "Tools for action",
      "description": "Tools for action",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142851/media/BerrypickingSearch.png",
      "type": "blog",
    },
    {
      "id": "my-summer-at-chapter-one",
      "date": "September 12, 2022",
      "title": "My Summer at Chapter One",
      "description": "My Summer at Chapter One",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142860/media/ChapterOneSummerBanner.png",
      "type": "blog",
    },
    {
      "id": "going-down-the-rabbit-hole",
      "date": "October 31, 2022",
      "title": "Going Down the Rabbit Hole",
      "description": "Going Down the Rabbit Hole",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142863/media/RabbitHoleBanner.jpg",
      "type": "blog",
    },
    {
      "id": "lego-blocks-for-the-web",
      "date": "December 15, 2022",
      "title": "LEGO Blocks for the Web",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142862/media/LEGOBlocksBanner.png",
      "type": "blog",
    },
    {
      "id": "2022-recap",
      "date": "January 5, 2023",
      "title": "2022 Recap",
      "description": "2022 Recap",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142851/media/2022Recap.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-jan-28-2023",
      "date": "January 28, 2023",
      "title": "Next in Tech - Jan. 28, 2023",
      "description": "Next in Tech - Jan. 28, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142855/media/NextInTechJan282023.png",
      "type": "blog",
    },
    {
      "id": "user-ai-gency",
      "date": "Feb 1, 2023",
      "title": "User AI-gency",
      "description": "User AI-gency",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142860/media/UserAIgency.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-feb-4-2023",
      "date": "Feb 4, 2023",
      "title": "Next in Tech - Feb. 4, 2023",
      "description": "Next in Tech - Feb. 4, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142854/media/NextInTechFeb42023.png",
      "type": "blog",
    },
    {
      "id": "building-a-digital-garden",
      "date": "Feb 10, 2023",
      "title": "Building a Digital Garden",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704144251/media/dsmetacard.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-feb-11-2023",
      "date": "Feb 11, 2023",
      "title": "Next in Tech - Feb. 11, 2023",
      "description": "Next in Tech - Feb. 11, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142856/media/NextInTechFeb112023.png",
      "type": "blog",
    },
    {
      "id": "the-boom-of-farcasters-developer-community",
      "date": "Feb 15, 2023",
      "title": "The Boom of Farcaster's Developer Community",
      "description": "The Boom of Farcaster's Developer Community, and how it mirrors early Twitter API excitement",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142858/media/TheBoomOfFarcastersDeveloperCommunity.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-feb-18-2023",
      "date": "Feb 18, 2023",
      "title": "Next in Tech - Feb. 18, 2023",
      "description": "Next in Tech - Feb. 18, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142855/media/NextInTechFeb182023.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-mar-4-2023",
      "date": "March 4, 2023",
      "title": "Next in Tech - Mar. 4, 2023",
      "description": "Next in Tech - Mar. 4, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142856/media/NextInTechMar42023.png",
      "type": "blog",
    },
    {
      "id": "internet-os",
      "date": "March 9, 2023",
      "title": "Internet OS",
      "description": "How the Internet will become a part of the operating system and what that looks like.",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142853/media/InternetOS.png",
      "type": "blog",
    },
    {
      "id": "the-wallet-of-tomorrow",
      "date": "March 14, 2023",
      "title": "The Wallet of Tomorrow",
      "description": "The Wallet of Tomorrow",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142858/media/TheWalletOfTomorrow.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-mar-20-2023",
      "date": "March 20, 2023",
      "title": "Next in Tech - Mar. 20, 2023",
      "description": "Next in Tech - Mar. 20, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142856/media/NextInTechMar202023.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-mar-25-2023",
      "date": "March 25, 2023",
      "title": "Next in Tech - Mar. 25, 2023",
      "description": "Next in Tech - Mar. 25, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142857/media/NextInTechMar252023.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-apr-1-2023",
      "date": "April 1, 2023",
      "title": "Next in Tech - Apr. 1, 2023",
      "description": "Next in Tech - Apr. 1, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142854/media/NextInTechApr12023.png",
      "type": "blog",
    },
    {
      "id": "product-launch-nfts",
      "date": "April 4, 2023",
      "title": "Product Launch NFTs",
      "description": "From Passive Collectors to Passionate Users",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142862/media/ProductLaunchNFTs.png",
      "type": "blog",
    },
    {
      "id": "next-in-tech-apr-8-2023",
      "date": "April 8, 2023",
      "title": "Next in Tech - Apr. 8, 2023",
      "description": "Next in Tech - Apr. 8, 2023",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142854/media/NextInTechApr82023.png",
      "type": "blog",
    },
    {
      "id": "shifting-directions",
      "date": "April 19, 2023",
      "title": "Shifting Directions",
      "description": "Shifting Directions",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142860/media/ShiftingDirections.png",
      "type": "blog",
    },
    {
      "id": "focus-on-what-doesnt-scale",
      "date": "June 4, 2023",
      "title": "Focus On What Doesn't Scale",
      "description": "Focus On What Doesn't Scale",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704142853/media/FocusOnWhatDoesntScale.png",
      "type": "blog",
    },
    {
      "id": "2023-recap",
      "date": "January 4, 2024",
      "title": "2023 Recap",
      "description": "My 2023 was defined by two things: a move to LA and going all in on projects",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1704345283/media/2023-recap-og-image.png",
      "type": "blog",
    },
    {
      "id": "onchain-nucleus",
      "date": "January 20, 2024",
      "title": "Onchain Nucleus",
      "description": "Read about why I think DAOs have a coordination problem and what an onchain nucleus can do to solve it",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1705785983/media/onchain-nucleus-og-image.png",
      "type": "blog",
    },
    {
      "id": "thoughts-on-building-a-farcaster-client",
      "date": "January 24, 2024",
      "title": "Thoughts on building a Farcaster client",
      "description": "Some thoughts on building a Farcaster client after spending some time building my own web & mobile client, Litecast.",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1706147355/media/thoughts-on-building-a-farcaster-client-og-image.png",
      "type": "blog"
    },
    {
      "id": "farcon-and-farhack-2024",
      "date": "May 13, 2024",
      "title": "FarCon and FarHack 2024",
      "description": "My notes and thoughts from the other week",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1715483513/media/farcon-and-farhack-2024-og-image.png",
      "type": "blog",
    },
    {
      "id": "crypto-super-app",
      "date": "May 18, 2024",
      "title": "Crypto Super App",
      "description": "Why everyone wants it but nobody is building it",
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1716068782/media/crypto-super-app-og-image.png",
      "type": "blog",
    },
    {
      "id": "free-fip-2",
      "date": "June 27, 2024",
      "title": "Free FIP-2",
      "description": `A brief overview of FIP-2 and why I think it's a key unlock for Farcaster's growth`,
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1719520174/media/free-fip-2-og-image.png",
      "type": "blog",
    },
    {
      "id": "cortex-one-pager",
      "date": "September 4, 2024",
      "title": "Cortex One Pager",
      "description": `I'm building a new product called Cortex, Notion-style blocks for Farcaster data. Below is a one-pager on the concept and its progress.`,
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1725492120/media/cortex-one-pager-sept-4-24.png",
      "type": "blog",
    },
    {
      "id": "farcaster-dev-day",
      "date": "September 27, 2024",
      "title": "Farcaster Dev Day",
      "description": `A recap from the inaugural Farcaster Dev Day in Venice Beach, CA.`,
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1727418648/media/farcaster-dev-day-sept-27-24.png",
      "type": "blog",
    },
    {
      "id": "universal-react",
      "date": "October 22, 2024",
      "title": "Universal React",
      "description": `A brief overview of some of the most exciting developments in the world of Universal React, what the main benefits/downfalls of those are, and what I think this all means for React developers`,
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1729569683/media/universal-react-oct-22-24.png",
      "type": "blog",
    },
    {
      "id": "2024-recap",
      "date": "January 7, 2025",
      "title": "2024 Recap",
      "description": 'An overview of everything I built and consumed in 2024',
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1736270857/media/2024-recap-jan-7-25.png",
      "type": "blog",
    },
    {
      "id": "the-farstack",
      "date": "March 10, 2025",
      "title": "The FarStack",
      "description": 'How the Farcaster ecosystem now has its own stack for consumer growth',
      "banner": "https://res.cloudinary.com/dz3c2rl2o/image/upload/v1741544009/media/the-farstack-mar-10-25.png",
      "type": "blog",
    }
  ];